<?php

namespace App\Filament\Resources\ProjectResource\Pages;

use App\Filament\Resources\ProjectResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditProject extends EditRecord
{
    protected static string $resource = ProjectResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        return $this->mergeTranslatableFields($data);
    }

    /**
     * Combine the per-language pseudo-fields (title_en, title_hi, etc.)
     * generated by the Tabs in the form back into the actual translatable
     * columns as {"en": "...", "hi": "..."} before the model is saved.
     */
    protected function mergeTranslatableFields(array $data): array
    {
        foreach (['title', 'locality', 'customer_quote', 'challenges_solved'] as $field) {
            $data[$field] = [
                'en' => $data[$field.'_en'] ?? '',
                'hi' => $data[$field.'_hi'] ?? '',
            ];

            unset($data[$field.'_en'], $data[$field.'_hi']);
        }

        return $data;
    }
}
