<?php

namespace App\Filament\Resources\ServiceResource\Pages;

use App\Filament\Resources\ServiceResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateService extends CreateRecord
{
    protected static string $resource = ServiceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        return $this->mergeTranslatableFields($data);
    }

    /**
     * Combine the per-language pseudo-fields (name_en, name_hi, etc.)
     * generated by the Tabs in the form back into the actual translatable
     * columns as {"en": "...", "hi": "..."} before the model is saved.
     */
    protected function mergeTranslatableFields(array $data): array
    {
        foreach (['name', 'short_description', 'long_description'] as $field) {
            $data[$field] = [
                'en' => $data[$field.'_en'] ?? '',
                'hi' => $data[$field.'_hi'] ?? '',
            ];

            unset($data[$field.'_en'], $data[$field.'_hi']);
        }

        return $data;
    }
}
